### ISSUE TITLE
먹이 및 물 배급방식

### ISSUE THREAD

**Issue by seok8418** [kuj0210/opensourceproject#10]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34744421/34338176-525ab364-e9a9-11e7-8aee-81eb211f1707.gif)

**Comment by KeonHeeLee** [comment]
404 에러뜨는데 실례가 되지 않는다면, Attach files로해서 동영상을 올려줘도 좋을거같아

**Comment by seok8418** [comment]
동영상은 지원안해서 gif로 일단 바꿨어
