### ISSUE TITLE
LINE 공식계정 홈페이지

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/opensourceproject#30]
https://partner.line.me/ko_KR

[문제] 기업관련으로만 받는듯 해서 요금이 있을 수도 있고 어디까지 오픈되어있는지 아직 미지수
관련정보 조사바람

**Comment by kuj0210** [comment]
공식계정 절차관련해서 LINE 공식블로그에 쪽지보냈습니다. 제발 무료이길... 라즈베리 주문하고 굶고있어요ㅜㅡㅜㅜ

**Comment by KeonHeeLee** [comment]
SSL 인증서를 발급받을려면 찾아보니깐 비용청구된다고 듣었음...
