### ISSUE TITLE
라즈베리파이 서버(PiServer Module) 작동방식의 스레드화

### ISSUE THREAD

**Issue by KeonHeeLee** [kuj0210/opensourceproject#37]
기존의 방식은 스레드라고해도 기기의 작동 시간에 따라서도 제대로 채팅을 못받아오는 경우도 있었음.
그러한 경우 때문에 채팅을 보내는 부분 따로, 작동을 하는 것을 따로 분리시키는 방식을 이용할 것.

또한 스레드를 사용하기 때문에 모터나 카메라가 작동하는 부분은 critical section이 되어야함.
즉, 이 부분은 사용중일 땐, 함부러 접근을 못하게 해야하므로 세마포어 같은 동기화를 사용해야함.

1. 채팅 보내는 부분 따로 분리시킬 것임.
2. 스레드화 시켜서 요청을 받아들이기에 세마포어를 사용해야함

**Comment by kuj0210** [comment]
저번에 이야기한것처럼 LOCK변수를 4개만들어서 진행해주고 모든 기능은 각 각 CS를 갖지만 카메라처럼 한정된 자원을 공유하는 기능들(사진/동영상)은 같은 CS안에서 동작할수 있게 해주세요.
