### ISSUE TITLE
추가/변경필요사항

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/opensourceproject#38]
챗봇
[현재]
지금 우리 챗봇은 질문을 받고 거기에 대한 단순 응신만 가능합니다. 즉, 단순방향 통신만 가능합니다.

이에 대해 추가적인 기능을 제안합니다 
[변경점] 
식사/급수/사진 등의 로그를 남겨 일정시간이 지나면 재실행을 권유
예 11시에 배식 -> 17시에 카카오톡에서 사용자에게 밥준지 6시간지났습니다 배식이 가능할가요? 하는 기능을 구현준비중. 현재 카카오 사이트에 문의중. 나온방법을 통해서 패턴적용해서 다른 메신저도 가능하게 분리된기능 고민중

DB
[현재]
유저가 카카오 하나뿐인 상황이라 하나의 테이블만 사용하여 조회

라인/페이스북 등 다른 메신저를 고려하려 테이블 분리필요, 각 메신저별 인풋을 확인하기 전까지는 진행이 어렵지만,
[변경점]  
기존: 유저테이블에서 조인하여 사용
변경: 메신저별 유저테이블 생성, 사용자를 구분하여 관리

**Comment by KeonHeeLee** [comment]
이런쪽이면 오히려 라인이 더 편리할 거 같은데, 자료를 좀 더 조사해서 올려보도록 하겠슴다

**Comment by kuj0210** [comment]
라인은 사용법이 조금 복잡한듯해서 멘토님 여쭤보고 하는게 어떨가 싶어요 우선은 알아두시고, 챗봇 API중에 문장분석해주는 기술이있다던데 그쪽관련 정보를 알아봐야할듯해요
