### ISSUE TITLE
서보모터 제어방법 조사

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/opensourceproject#5]
좌우 방향제어 및 시간동안 회전하는 방법

**Comment by seok8418** [comment]
-2초간 한쪽 방향으로 회전-
import RPi.GPIO as GPIO
import time
pin = 18

GPIO.setmode(GPIO.BCM)
GPIO.setup(pin, GPIO.OUT)
p = GPIO.PWM(pin, 50)
p.start(0)
try:
    p.ChangeDutyCycle(8)#8 or 0
    time.sleep(2)
    p.stop()
except KeyboardInterrupt:
    p.stop()
GPIO.cleanup()
